// themes/src/main/resources/theme/keycloak-preview/account/resources/app/content/device-activity-page/device-activity-page.component.ts
/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, OnInit, ViewChild} from '@angular/core';
import {Response} from '@angular/http';
import {FormGroup} from '@angular/forms';

import {AccountServiceClient} from '../../account-service/account.service';

@Component({
    selector: 'app-device-activity-page',
    templateUrl: './device-activity-page.component.html',
    styleUrls: ['./device-activity-page.component.css']
})
export class DeviceActivityPageComponent implements OnInit {

    @ViewChild('formGroup') private formGroup: FormGroup;
    
    constructor(private accountSvc: AccountServiceClient) {
    }
    
    public deviceActivity() {
        console.log("posting: " + JSON.stringify(this.formGroup.value));
        this.accountSvc.doPostRequest("/device-activity", (res: Response) => this.handlePostResponse(res), this.formGroup.value);
    }
    
    protected handlePostResponse(res: Response) {
      console.log('**** response from account POST ***');
      console.log(JSON.stringify(res));
      console.log('***************************************');
    }

    ngOnInit() {
    }
}

<div class="page-header">
  <h1>{{'deviceActivityHtmlTitle' | translate}}</h1>
</div>

<div class="row row-cards-pf">
  <div class="col-md-12">
    <div class="card-pf card-pf-utilization" style="">
      <div>
        <button class="btn btn-default pull-right" type="button" data-toggle="modal" data-target="#myModal">Log Out All Devices</button>
        <h2 class="card-pf-title" style="">
          Signed In Devices
        </h2>
        <p class="detail-description">You can find devices that have logged into your account from the list. Log out any of them if the device is unfamiliar or logged in wrong place and time.</p>

      </div>
      <div class="card-pf-body" style="">
        <div class="row">
         <div class="container-fluid">
          <div id="pf-list-simple-expansion" class="list-group list-view-pf list-view-pf-view">
            <div class="list-group-item">
              <div class="list-group-item-header">
                <div class="list-view-pf-expand">
                  <span class="fa fa-angle-right"></span>
                </div>

                <div class="list-view-pf-main-info">
                  <div class="list-view-pf-left">
                    <span class="fa fa-desktop list-view-pf-icon-sm"></span>
                  </div>
                  <div class="list-view-pf-body">
                    <div class="list-view-pf-description">
                      <div class="list-group-item-heading">
                        Asus A3G
                      </div>
                      <div class="list-group-item-text current-color">
                        Current device
                      </div>
                    </div>

                  </div>
                </div>
              </div>
              <div class="list-group-item-container container-fluid hidden">
                <div class="close">
                  <span class="pficon pficon-close"></span>
                </div>

                <div id="utilizationDonutChart11" class="example-donut-chart-utilization"></div>
                <div class="activity-item">
                  <ul>
                    <li><h3><i class="fa fa-firefox"></i> Firefox on OS X 10.11</h3></li>
                    <li><b>Last accessed in</b> Dalian, China (219.147.95.224) <b>on</b> January 8, 17:33:52</li>
                    <li><b>Clients</b> security-admin-console, account</li>
                    <li><span><b>Started at</b> January 8, 3:25:38</span> <span class="m-l"><b>Expires at</b> January 9, 3:25:37</span></li>
                  </ul>

                  <!-- Button trigger modal -->
                  <button type="button" class="btn btn-default btn-logout" data-toggle="modal" data-target="#myModal">Log Out</button>
                  <!-- End Button trigger modal -->
                </div>

                <div class="activity-item">
                  <ul>
                    <li><h3><i class="fa fa-chrome"></i> Chrome on OS X 10.11.6</h3></li>
                    <li><b>Last accessed in</b> Dalian, China (219.147.95.224) <b>on</b> January 8, 17:33:52</li>
                    <li><b>Clients</b> security-admin-console, account</li>
                    <li><span><b>Started at</b> January 8, 3:25:38</span> <span class="m-l"><b>Expires at</b> January 9, 3:25:37</span></li>
                  </ul>
                  <button class="btn btn-default btn-logout">Log Out</button>
                </div>
              </div>
            </div>
            <div class="list-group-item">
              <div class="list-group-item-header">
                <div class="list-view-pf-expand">
                  <span class="fa fa-angle-right"></span>
                </div>

                <div class="list-view-pf-main-info">
                  <div class="list-view-pf-left">
                    <span class="fa fa-mobile list-view-pf-icon-sm"></span>
                  </div>
                  <div class="list-view-pf-body">
                    <div class="list-view-pf-description">
                      <div class="list-group-item-heading">
                        Asus A3G
                      </div>
                      <div class="list-group-item-text">
                        <b>Last Access</b>
                        <span>Raleigh, US - January 8, 17:33:52</span>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
              <div class="list-group-item-container container-fluid hidden">
                <div class="close">
                  <span class="pficon pficon-close"></span>
                </div>
                <div class="activity-item">
                  <ul>
                    <li><h3><i class="fa fa-firefox"></i> Firefox on OS X 10.11</h3></li>
                    <li><b>Last accessed in</b> Dalian, China (219.147.95.224) <b>on</b> January 8, 17:33:52</li>
                    <li><b>Clients</b> security-admin-console, account</li>
                    <li><span><b>Started at</b> January 8, 3:25:38</span> <span class="m-l"><b>Expires at</b> January 9, 3:25:37</span></li>
                  </ul>
                  <button class="btn btn-default btn-logout">Log Out</button>
                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card-pf card-pf-utilization" style="">
      <div>
        <h2 class="card-pf-title" style="">
          Recently Used Devices
        </h2>
        <p class="detail-description">You can find devices that you used in the last month, but they have not logged into your account anymore.</p>

      </div>
      <div class="card-pf-body" style="">
        <div class="row">
         <div class="container-fluid">

           <div id="pf-list-simple-expansion" class="list-group list-view-pf list-view-pf-view">

            <div class="list-group-item">
              <div class="list-group-item-header">
                <div class="list-view-pf-expand">
                  <span class="fa fa-angle-right"></span>
                </div>

                <div class="list-view-pf-main-info">
                  <div class="list-view-pf-left">
                    <span class="fa fa-mobile list-view-pf-icon-sm"></span>
                  </div>
                  <div class="list-view-pf-body">
                    <div class="list-view-pf-description">
                      <div class="list-group-item-heading">
                        Asus A3G
                      </div>
                      <div class="list-group-item-text">
                        <b>Last Access</b>
                        <span>Raleigh, US - January 8, 17:33:52</span>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
              <div class="list-group-item-container container-fluid hidden">
                <div class="close">
                  <span class="pficon pficon-close"></span>
                </div>
                <div class="activity-item">
                  <ul>
                    <li><h3><i class="fa fa-firefox"></i> Firefox on OS X 10.11</h3></li>
                    <li><b>Last accessed in</b> Dalian, China (219.147.95.224) <b>on</b> January 8, 17:33:52</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>

      </div>
    </div>

  </div>
</div>

<!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Log Out All Devices</h4>
          </div>
          <div class="modal-body">
            Logging Out All Devices will log out all the devices that have signed in to your account, including the current device you are using.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-primary">Log Out</button>
          </div>
        </div>
      </div>
    </div>
<!-- End Modal -->


<script>
$(document).ready(function () {
  // click the list-view heading then expand a row
  $("#pf-list-simple-expansion .list-group-item-header").click(function(event){
    if(!$(event.target).is("button, a, input, .fa-ellipsis-v")){
      $(this).find(".fa-angle-right").toggleClass("fa-angle-down")
      .end().parent().toggleClass("list-view-pf-expand-active")
      .find(".list-group-item-container").toggleClass("hidden");
    } else {
    }
  })

  // click the close button, hide the expand row and remove the active status
  $("#pf-list-simple-expansion .list-group-item-container .close").on("click", function (){
    $(this).parent().addClass("hidden")
    .parent().removeClass("list-view-pf-expand-active")
    .find(".fa-angle-right").removeClass("fa-angle-down");
  })

});
</script>

// themes/src/main/resources/theme/keycloak.v2/account/src/app/content/device-activity-page/DeviceActivityPage.tsx
/*
 * Copyright 2018 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';

import {HttpResponse} from '../../account-service/account.service';
import { AccountServiceContext } from '../../account-service/AccountServiceContext';
import TimeUtil from '../../util/TimeUtil';

import {
  Button,
  DataList,
  DataListItem,
  DataListItemRow,
  DataListContent,
  DescriptionList,
  DescriptionListTerm,
  DescriptionListDescription,
  DescriptionListGroup,
  Grid,
  GridItem,
  Label,
  PageSection,
  PageSectionVariants,
  Title,
  Tooltip,
  SplitItem,
  Split
} from '@patternfly/react-core';

import {
        DesktopIcon,
        MobileAltIcon,
        SyncAltIcon,
} from '@patternfly/react-icons';

import {Msg} from '../../widgets/Msg';
import {ContinueCancelModal} from '../../widgets/ContinueCancelModal';
import { KeycloakService } from '../../keycloak-service/keycloak.service';
import { KeycloakContext } from '../../keycloak-service/KeycloakContext';

import {ContentPage} from '../ContentPage';
import { ContentAlert } from '../ContentAlert';

export interface DeviceActivityPageProps {
}

export interface DeviceActivityPageState {
  devices: Device[];
}

interface Device {
  browser: string;
  current: boolean;
  device: string;
  ipAddress: string;
  lastAccess: number;
  mobile: boolean;
  os: string;
  osVersion: string;
  sessions: Session[];
}

interface Session {
  browser: string;
  current: boolean;
  clients: Client[];
  expires: number;
  id: string;
  ipAddress: string;
  lastAccess: number;
  started: number;
}

interface Client {
  clientId: string;
  clientName: string;
}

/**
 * @author Stan Silvert ssilvert@redhat.com (C) 2019 Red Hat Inc.
 */
export class DeviceActivityPage extends React.Component<DeviceActivityPageProps, DeviceActivityPageState> {
    static contextType = AccountServiceContext;
    context: React.ContextType<typeof AccountServiceContext>;

    public constructor(props: DeviceActivityPageProps, context: React.ContextType<typeof AccountServiceContext>) {
        super(props);
        this.context = context;

        this.state = {
          devices: []
        };

        this.fetchDevices();
    }

    private signOutAll = (keycloakService: KeycloakService) => {
      this.context!.doDelete("/sessions")
        .then( () => {
          keycloakService.logout();
        });
    }

    private signOutSession = (device: Device, session: Session) => {
      this.context!.doDelete("/sessions/" + session.id)
          .then (() => {
            this.fetchDevices();
            ContentAlert.success('signedOutSession', [session.browser, device.os]);
          });
    }

    private fetchDevices(): void {
      this.context!.doGet<Device[]>("/sessions/devices")
          .then((response: HttpResponse<Device[]>) => {
            console.log({response});

            let devices: Device[] = this.moveCurrentToTop(response.data as Device[]);

            this.setState({
              devices: devices
            });

          });
    }

    // current device and session should display at the top of their respective lists
    private moveCurrentToTop(devices: Device[]): Device[] {
      let currentDevice: Device = devices[0];

      devices.forEach((device: Device, index: number) => {
        if (device.current) {
          currentDevice = device;
          devices.splice(index, 1);
          devices.unshift(device);
        }
      });

      currentDevice.sessions.forEach((session: Session, index: number) => {
        if (session.current) {
          const currentSession: Session[] = currentDevice.sessions.splice(index, 1);
          currentDevice.sessions.unshift(currentSession[0]);
        }
      });

      return devices;
    }

    private time(time: number): string {
      return TimeUtil.format(time * 1000);
    }

    private elementId(item: string, session: Session, element: string='session'): string {
        return `${element}-${session.id.substring(0,7)}-${item}`;
    }

    private findDeviceTypeIcon(session: Session, device: Device): React.ReactNode {
      const deviceType: boolean = device.mobile;
      if (deviceType === true) return (<MobileAltIcon id={this.elementId('icon-mobile', session, 'device')} />);

      return (<DesktopIcon id={this.elementId('icon-desktop', session, 'device')} />);
    }

    private findOS(device: Device): string {
      if (device.os.toLowerCase().includes('unknown')) return Msg.localize('unknownOperatingSystem');

      return device.os;
    }

    private findOSVersion(device: Device): string {
      if (device.osVersion.toLowerCase().includes('unknown')) return '';

      return device.osVersion;
    }

    private makeClientsString(clients: Client[]): string {
      let clientsString = "";
      clients.forEach( (client: Client, index: number) => {
        let clientName: string;
        if (client.hasOwnProperty('clientName') && (client.clientName !== undefined) && (client.clientName !== '')) {
          clientName = Msg.localize(client.clientName);
        } else {
          clientName = client.clientId;
        }

        clientsString += clientName;

        if (clients.length > index + 1) clientsString += ', ';
      })

      return clientsString;
    }

    private isShowSignOutAll(devices: Device[]): boolean {
      if (devices.length === 0) return false;
      if (devices.length > 1) return true;
      if (devices[0].sessions.length > 1) return true;

      return false;
    }

    public render(): React.ReactNode {

      return (
          <ContentPage 
            title="device-activity" 
            introMessage="signedInDevicesExplanation" 
          >
            <PageSection isFilled variant={PageSectionVariants.light}>
            <Split hasGutter className="pf-u-mb-lg">
              <SplitItem isFilled>
                <div id="signedInDevicesTitle" className="pf-c-content"><Title headingLevel="h2" size="xl"><Msg msgKey="signedInDevices"/></Title></div>
              </SplitItem>
              <SplitItem>
                <Tooltip content={<Msg msgKey="refreshPage" />}>
                  <Button
                    aria-describedby="refresh page"
                    id="refresh-page"
                    variant="link"
                    onClick={this.fetchDevices.bind(this)}
                    icon={<SyncAltIcon />}
                  >
                    <Msg msgKey="refresh"/>
                  </Button>
                </Tooltip>
              </SplitItem>
              <SplitItem>
              <KeycloakContext.Consumer>
                { (keycloak: KeycloakService) => (
                    this.isShowSignOutAll(this.state.devices) &&
                      <ContinueCancelModal buttonTitle='signOutAllDevices'
                                    buttonId='sign-out-all'
                                    modalTitle='signOutAllDevices'
                                    modalMessage='signOutAllDevicesWarning'
                                    onContinue={() => this.signOutAll(keycloak)}
                      />
                )}
              </KeycloakContext.Consumer>
              </SplitItem>
            </Split>
            <DataList className="signed-in-device-list" aria-label={Msg.localize('signedInDevices')}>
              <DataListItem aria-labelledby='sessions' id='device-activity-sessions'>
                {this.state.devices.map((device: Device, deviceIndex: number) => {
                  return (
                    <React.Fragment>
                      {device.sessions.map((session: Session, sessionIndex: number) => {
                        return (
                          <React.Fragment key={'device-' + deviceIndex + '-session-' + sessionIndex}>
                            <DataListItemRow>
                              <DataListContent aria-label="device-sessions-content" isHidden={false} className="pf-u-flex-grow-1">
                                <Grid id={this.elementId("item",session)} className="signed-in-device-grid" hasGutter>
                                  <GridItem className="device-icon" span={1} rowSpan={2}>
                                    <span>{this.findDeviceTypeIcon(session, device)}</span>
                                  </GridItem>
                                  <GridItem sm={8} md={9} span={10}>
                                    <span id={this.elementId('browser', session)} className="pf-u-mr-md session-title">{this.findOS(device)} {this.findOSVersion(device)} / {session.browser}</span>
                                    {session.current &&
                                      <Label color="green" id={this.elementId('current-badge', session)}><Msg msgKey="currentSession" /></Label>}
                                  </GridItem>
                                  <GridItem className="pf-u-text-align-right" sm={3} md={2} span={1}>
                                    {!session.current &&
                                      <ContinueCancelModal buttonTitle='doSignOut'
                                        buttonId={this.elementId('sign-out', session)}
                                        modalTitle='doSignOut'
                                        buttonVariant='secondary'
                                        modalMessage='signOutWarning'
                                        onContinue={() => this.signOutSession(device, session)}
                                      />
                                    }
                                  </GridItem>
                                  <GridItem span={11}>
                                    <DescriptionList columnModifier={{ sm: '2Col', lg: '3Col' }}>
                                      <DescriptionListGroup>
                                        <DescriptionListTerm>{Msg.localize('ipAddress')}</DescriptionListTerm>
                                          <DescriptionListDescription id={this.elementId('ip', session)}>{session.ipAddress}</DescriptionListDescription>
                                      </DescriptionListGroup>
                                      <DescriptionListGroup>
                                          <DescriptionListTerm>{Msg.localize('lastAccessedOn')}</DescriptionListTerm>
                                          <DescriptionListDescription id={this.elementId('last-access', session)}>{this.time(session.lastAccess)}</DescriptionListDescription>
                                      </DescriptionListGroup>
                                      <DescriptionListGroup>
                                          <DescriptionListTerm>{Msg.localize('clients')}</DescriptionListTerm>
                                          <DescriptionListDescription id={this.elementId('clients', session)}>{this.makeClientsString(session.clients)}</DescriptionListDescription>
                                      </DescriptionListGroup>
                                      <DescriptionListGroup>
                                        <DescriptionListTerm>{Msg.localize('started')}</DescriptionListTerm>
                                        <DescriptionListDescription id={this.elementId('started', session)}>{this.time(session.started)}</DescriptionListDescription>
                                      </DescriptionListGroup>
                                      <DescriptionListGroup>
                                        <DescriptionListTerm>{Msg.localize('expires')}</DescriptionListTerm>
                                        <DescriptionListDescription id={this.elementId('expires', session)}>{this.time(session.expires)}</DescriptionListDescription>
                                      </DescriptionListGroup>
                                    </DescriptionList>
                                  </GridItem>
                                </Grid>
                              </DataListContent>
                            </DataListItemRow>
                          </React.Fragment>
                        );
                      })}
                    </React.Fragment>
                  )
                })}
              </DataListItem>
            </DataList>
          </PageSection>
        </ContentPage>
      );
    }
};
