// themes/src/main/resources/theme/keycloak-preview/account/resources/app/content/authenticator-page/authenticator-page.component.ts
/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, OnInit} from '@angular/core';

@Component({
    selector: 'app-authenticator-page',
    templateUrl: './authenticator-page.component.html',
    styleUrls: ['./authenticator-page.component.css']
})
export class AuthenticatorPageComponent implements OnInit {

    constructor() {
    }

    ngOnInit() {
    }

}

<div class="page-header">
    <h1 id="pageTitle">{{'authenticatorTitle' | translate}}</h1>
</div>

<div class="col-sm-12 card-pf">
  <div class="card-pf-body p-b">
    <span class="label label-default m-r" id="authenticatorStatus">OFF</span>
    <!-- <span class="label label-primary m-r">ON</span> -->
    {{'authenticatorStatusMessage' | translate}} off
  </div>
</div>

<div class="col-sm-12 card-pf">
  <div class="card-pf-body row">
    <div class="col-sm-4 col-md-4">
      <div class="card-pf-subtitle" id="authenticatorFinishSetUpTitle">
          {{'authenticatorFinishSetUpTitle' | translate}}
      </div>
      <div class="introMessage" id="authenticatorFinishSetUpMessage">
          <p>{{'authenticatorFinishSetUpMessage' | translate}}</p>
      </div>
    </div>
    <div class="col-sm-8 col-md-8">
      <div class="list-pf list-pf-stacked list-authenticator" id="authenticatorFinishList">
        <div class="list-authenticator-item">
          <div class="list-pf-container">
            <div class="list-pf-content list-pf-content-flex ">
              <div class="list-pf-left">
                <span class="fa fa-google list-pf-icon"></span>
              </div>
              <div class="list-pf-content-wrapper">
                <div class="list-pf-main-content">
                  <div class="list-pf-title text-overflow-pf">
                    {{'authenticatorMobileTitle' | translate}}
                    <span class="label label-default authenticator-label">{{'authenticatorDefaultStatus' | translate}}</span>
                  </div>
                  <div class="list-pf-description">
                    {{'authenticatorMobileFinishSetUpMessage' | translate}}
                  </div>
                  <div class="top-margin-m authenticator-entry">
                    <a href="javascript:void(0)">{{'authenticatorChangePhone' | translate}}</a>
                  </div>
                </div>
              </div>
              <div class="list-pf-actions">
                <div class="dropdown pull-right dropdown-kebab-pf">
                  <button id="dropdownKebabRight" class="btn btn-link dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span class="fa fa-ellipsis-v"></span>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownKebabRight">
                    <li><a href="javascript:void(0)">{{'doRemove' | translate}}</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-sm-12 card-pf">
  <div class="card-pf-body row">
    <div class="col-sm-4 col-md-4">
      <div class="card-pf-subtitle" id="authenticatorSubTitle">
          {{'authenticatorSubTitle' | translate}}
      </div>
      <div class="introMessage" id="authenticatorSubMessage">
          <p>{{'authenticatorSubMessage' | translate}}</p>
      </div>
    </div>
    <div class="col-sm-8 col-md-8">
      <div class="list-pf list-pf-stacked list-authenticator" id="authenticatorList">
        <div class="list-authenticator-item">
          <div class="list-pf-container">
            <div class="list-pf-content list-pf-content-flex">
              <div class="list-pf-left">
                <span class="fa fa-mobile list-pf-icon"></span>
              </div>
              <div class="list-pf-content-wrapper">
                <div class="list-pf-main-content">
                  <div class="list-pf-title text-overflow-pf">{{'authenticatorSMSTitle' | translate}}</div>
                  <div class="list-pf-description">{{'authenticatorSMSMessage' | translate}}</div>
                </div>
              </div>
              <div class="list-pf-actions">
                <a class="btn btn-link" href="javascript:void(0)">{{'authenticatorActionSetup' | translate}}</a>
              </div>
            </div>
          </div>
        </div>
        <div class="list-authenticator-item">
          <div class="list-pf-container">
            <div class="list-pf-content list-pf-content-flex ">
              <div class="list-pf-left">
                <span class="fa fa-lock list-pf-icon list-pf-icon-large"></span>
              </div>
              <div class="list-pf-content-wrapper">
                <div class="list-pf-main-content">
                  <div class="list-pf-title text-overflow-pf">{{'authenticatorBackupCodesTitle' | translate}}</div>
                  <div class="list-pf-description">{{'authenticatorBackupCodesMessage' | translate}}</div>
                </div>
              </div>
              <div class="list-pf-actions">
                <a class="btn btn-link" href="javascript:void(0)">{{'authenticatorActionSetup' | translate}}</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// themes/src/main/resources/theme/keycloak.v2/account/src/app/content/authenticator-page/AuthenticatorPage.tsx
/* 
 * Copyright 2018 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';
 
export interface AuthenticatorPageProps {
}
 
export class AuthenticatorPage extends React.Component<AuthenticatorPageProps> {
    
    public constructor(props: AuthenticatorPageProps) {
        super(props);
    }

    public render(): React.ReactNode {
        return (
            <div>
              <h2>Hello Authenticator Page</h2>
            </div>
        );
    }
};
