// themes/src/main/resources/theme/keycloak-preview/account/resources/app/content/password-page/PasswordPage.tsx
/* 
 * Copyright 2018 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';
import * as moment from 'moment';
import {AxiosResponse} from 'axios';

import {AccountServiceClient} from '../../account-service/account.service';
import {Msg} from '../../widgets/Msg';
 
export interface PasswordPageProps {
}

interface FormFields {
    readonly currentPassword?: string;
    readonly newPassword?: string;
    readonly confirmation?: string;
}

interface PasswordPageState {
    readonly canSubmit: boolean,
    readonly registered: boolean;
    readonly lastUpdate: number;
    readonly formFields: FormFields;
}

export class PasswordPage extends React.Component<PasswordPageProps, PasswordPageState> {
    state: PasswordPageState = {
        canSubmit: false,
        registered: false,
        lastUpdate: -1,
        formFields: {currentPassword: '',
                     newPassword: '',
                     confirmation: ''}
    }
    
    constructor(props: PasswordPageProps) {
        super(props);
        
        AccountServiceClient.Instance.doGet("/credentials/password")
            .then((response: AxiosResponse<PasswordPageState>) => {
                this.setState({...response.data});
                console.log({response});
            });
    }
    
    private handleChange = (event: React.ChangeEvent<HTMLInputElement>): void => {
        const target: HTMLInputElement = event.target;
        const value: string = target.value;
        const name: string = target.name;
        this.setState({
            canSubmit: this.requiredFieldsHaveData(name, value),
            registered: this.state.registered,
            lastUpdate: this.state.lastUpdate,
            formFields: {...this.state.formFields, [name]: value}
        });
    }
    
    private handleSubmit = (event: React.FormEvent<HTMLFormElement>): void => {
        event.preventDefault();
        const reqData: FormFields = {...this.state.formFields};
        AccountServiceClient.Instance.doPost("/credentials/password", {data: reqData})
            .then((response: AxiosResponse<FormFields>) => {
                this.setState({canSubmit: false});
                alert('Data posted');
            });
    }
    
    private requiredFieldsHaveData(fieldName: string, newValue: string): boolean { 
        const fields: FormFields = {...this.state.formFields};
        fields[fieldName] = newValue;
        for (const field of Object.keys(fields)) {
            if (!fields[field]) return false;
        }
        
        return true;
    }

    render() {
        const displayNone = {display: 'none'};
        
        return (
<div>
    <div className="page-header">
        <h1 id="pageTitle"><Msg msgKey="changePasswordHtmlTitle"/></h1>
    </div>
    
    <div className="col-sm-12 card-pf">
        <div className="card-pf-body p-b" id="passwordLastUpdate">
            <span className="i pficon pficon-info"></span>
            <Msg msgKey="passwordLastUpdateMessage" /> <strong>{moment(this.state.lastUpdate).format('LLLL')}</strong>
        </div>
    </div>

    <div className="col-sm-12 card-pf">
        <div className="card-pf-body row">
            <div className="col-sm-4 col-md-4">
                <div className="card-pf-subtitle" id="updatePasswordSubTitle">
                    <Msg msgKey="updatePasswordTitle"/>
                </div>
                <div className="introMessage" id="updatePasswordSubMessage">
                    <strong><Msg msgKey="updatePasswordMessageTitle"/></strong>
                    <p><Msg msgKey="updatePasswordMessage"/></p>
                </div>
                <div className="subtitle"><span className="required">*</span> <Msg msgKey="requiredFields"/></div>
            </div>
            <div className="col-sm-6 col-md-6">
                <form onSubmit={this.handleSubmit} className="form-horizontal">
                    <input readOnly value="this is not a login form" style={displayNone} type="text"/>
                    <input readOnly value="this is not a login form" style={displayNone} type="password"/>
                    <div className="form-group">
                        <label htmlFor="password" className="control-label"><Msg msgKey="currentPassword"/></label><span className="required">*</span>
                        <input onChange={this.handleChange} className="form-control" name="currentPassword" autoFocus autoComplete="off" type="password"/>
                    </div>

                    <div className="form-group">
                        <label htmlFor="password-new" className="control-label"><Msg msgKey="passwordNew"/></label><span className="required">*</span>
                        <input onChange={this.handleChange} className="form-control" id="newPassword" name="newPassword" autoComplete="off" type="password"/>
                    </div>

                    <div className="form-group">
                        <label htmlFor="password-confirm" className="control-label"><Msg msgKey="passwordConfirm"/></label><span className="required">*</span>
                        <input onChange={this.handleChange} className="form-control" id="confirmation" name="confirmation" autoComplete="off" type="password"/>
                    </div>

                    <div className="form-group">
                        <div id="kc-form-buttons" className="submit">
                            <div className="">
                                <button disabled={!this.state.canSubmit} 
                                        type="submit" 
                                        className="btn btn-primary btn-lg" 
                                        name="submitAction"><Msg msgKey="doSave"/></button>
                            </div>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>
        );
    }
};

// themes/src/main/resources/theme/keycloak-preview/account/resources/app/content/password-page/password-page.component.ts
/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, OnInit, ViewChild, Renderer2} from '@angular/core';
import {Response} from '@angular/http';
import {FormGroup} from '@angular/forms';

import {AccountServiceClient} from '../../account-service/account.service';

@Component({
    selector: 'app-password-page',
    templateUrl: './password-page.component.html',
    styleUrls: ['./password-page.component.css']
})
export class PasswordPageComponent implements OnInit {

    @ViewChild('formGroup') private formGroup: FormGroup;
    private lastPasswordUpdate: number;
    
    constructor(private accountSvc: AccountServiceClient, private renderer: Renderer2) {
        this.accountSvc.doGetRequest("/credentials/password", (res: Response) => this.handleGetResponse(res));
    }
    
    public changePassword() {
        console.log("posting: " + JSON.stringify(this.formGroup.value));
        this.accountSvc.doPostRequest("/credentials/password", (res: Response) => this.handlePostResponse(res), this.formGroup.value);
        this.renderer.selectRootElement('#password').focus();
    }
    
    protected handlePostResponse(res: Response) {
      console.log('**** response from account POST ***');
      console.log(JSON.stringify(res));
      console.log('***************************************');
      this.formGroup.reset();
      this.accountSvc.doGetRequest("/credentials/password", (res: Response) => this.handleGetResponse(res));
    }
    
    protected handleGetResponse(res: Response) {
        console.log('**** response from account POST ***');
        console.log(JSON.stringify(res));
        console.log('***************************************');
        this.lastPasswordUpdate = res.json()['lastUpdate'];
    }

    ngOnInit() {
    }
}

<div class="page-header">
    <h1>{{'changePasswordHtmlTitle' | translate}}</h1>
</div>

<div class="col-sm-12 card-pf">
  <div class="card-pf-body p-b">
    <span class="i pficon pficon-info"></span>
    {{'passwordLastUpdateMessage' | translate}} <strong>{{lastPasswordUpdate | date:'medium'}}</strong>
  </div>
</div>

<div class="col-sm-12 card-pf">
    <div class="card-pf-body row">
        <div class="col-sm-4 col-md-4">
            <div class="card-pf-subtitle">
                {{'updatePasswordTitle' | translate}}
            </div>
            <div class="introMessage">
                <strong>{{'updatePasswordMessageTitle' | translate}}</strong>
                <p>{{'updatePasswordMessage' | translate}}</p>
            </div>
            <div class="subtitle"><span class="required">*</span> {{'requiredFields' | translate}}</div>
        </div>
        <div class="col-sm-6 col-md-6">
          <form #formGroup="ngForm" (ngSubmit)="changePassword()" class="form-horizontal">
            <input readonly="" value="this is not a login form" style="display: none;" type="text">
            <input readonly="" value="this is not a login form" style="display: none;" type="password">
            <div class="form-group">
                <label for="password" class="control-label">{{'currentPassword' | translate}}</label><span class="required">*</span>
                <input ngModel class="form-control" #password id="password" name="currentPassword" autofocus="" autocomplete="off" type="password">
            </div>

            <div class="form-group">
                <label for="password-new" class="control-label">{{'passwordNew' | translate}}</label><span class="required">*</span>
                <input ngModel class="form-control" id="newPassword" name="newPassword" autocomplete="off" type="password">
            </div>

            <div class="form-group">
                <label for="password-confirm" class="control-label">{{'passwordConfirm' | translate}}</label><span class="required">*</span>
                <input ngModel class="form-control" id="confirmation" name="confirmation" autocomplete="off" type="password">
            </div>

            <div class="form-group">
                <div id="kc-form-buttons" class="submit">
                    <div class="">
                        <button type="submit" class="btn btn-primary btn-lg" name="submitAction">{{'doSave' | translate}}</button>
                    </div>
                </div>
            </div>
          </form>
      </div>
  </div>
</div>
