// themes/src/main/resources/theme/keycloak.v2/account/src/app/content/linked-accounts-page/LinkedAccountsPage.tsx
/*
 * Copyright 2019 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';
import {withRouter, RouteComponentProps} from 'react-router-dom';

import {
    Badge,
    Button,
    DataList,
    DataListAction,
    DataListItemCells,
    DataListCell,
    DataListItemRow,
    Stack,
    StackItem,
    Title,
    DataListItem,
} from '@patternfly/react-core';

import {
    BitbucketIcon,
    CubeIcon,
    FacebookIcon,
    GithubIcon,
    GitlabIcon,
    GoogleIcon,
    InstagramIcon,
    LinkIcon,
    LinkedinIcon,
    MicrosoftIcon,
    OpenshiftIcon,
    PaypalIcon,
    StackOverflowIcon,
    TwitterIcon,
    UnlinkIcon
} from '@patternfly/react-icons';

import {HttpResponse} from '../../account-service/account.service';
import {AccountServiceContext} from '../../account-service/AccountServiceContext';
import {Msg} from '../../widgets/Msg';
import {ContentPage} from '../ContentPage';
import {createRedirect} from '../../util/RedirectUri';

interface LinkedAccount {
    connected: boolean;
    social: boolean;
    providerAlias: string;
    providerName: string;
    displayName: string;
    linkedUsername: string;
}

interface LinkedAccountsPageProps extends RouteComponentProps {
}

interface LinkedAccountsPageState {
    linkedAccounts: LinkedAccount[];
    unLinkedAccounts: LinkedAccount[];
}

/**
 * @author Stan Silvert
 */
class LinkedAccountsPage extends React.Component<LinkedAccountsPageProps, LinkedAccountsPageState> {
    static contextType = AccountServiceContext;
    context: React.ContextType<typeof AccountServiceContext>;

    public constructor(props: LinkedAccountsPageProps, context: React.ContextType<typeof AccountServiceContext>) {
        super(props);
        this.context = context;

        this.state = {
            linkedAccounts: [],
            unLinkedAccounts: []
        }

        this.getLinkedAccounts();
    }

    private getLinkedAccounts(): void {
        this.context!.doGet<LinkedAccount[]>("/linked-accounts")
            .then((response: HttpResponse<LinkedAccount[]>) => {
                console.log({response});
                const linkedAccounts = response.data!.filter((account) => account.connected);
                const unLinkedAccounts = response.data!.filter((account) => !account.connected);
                this.setState({linkedAccounts: linkedAccounts, unLinkedAccounts: unLinkedAccounts});
            });
    }

    private unLinkAccount(account: LinkedAccount): void {
        const url = '/linked-accounts/' + account.providerName;

        this.context!.doDelete<void>(url)
            .then((response: HttpResponse<void>) => {
                console.log({response});
                this.getLinkedAccounts();
            });
    }

    private linkAccount(account: LinkedAccount): void {
        const url = '/linked-accounts/' + account.providerName;

        const redirectUri: string = createRedirect(this.props.location.pathname);

        this.context!.doGet<{accountLinkUri: string}>(url, { params: {providerId: account.providerName, redirectUri}})
            .then((response: HttpResponse<{accountLinkUri: string}>) => {
                console.log({response});
                window.location.href = response.data!.accountLinkUri;
            });
    }

    public render(): React.ReactNode {

        return (
            <ContentPage title={Msg.localize('linkedAccountsTitle')} introMessage={Msg.localize('linkedAccountsIntroMessage')}>
                <Stack hasGutter>
                    <StackItem isFilled>
                        <Title headingLevel="h2" size='2xl'>
                            <Msg msgKey='linkedLoginProviders'/>
                        </Title>
                        <DataList id="linked-idps" aria-label='foo'>
                            {this.makeRows(this.state.linkedAccounts, true)}
                        </DataList>
                    </StackItem>
                    <StackItem isFilled/>
                    <StackItem isFilled>
                        <Title headingLevel="h2" size='2xl'>
                            <Msg msgKey='unlinkedLoginProviders'/>
                        </Title>
                        <DataList id="unlinked-idps" aria-label='foo'>
                            {this.makeRows(this.state.unLinkedAccounts, false)}
                        </DataList>
                    </StackItem>
                </Stack>
            </ContentPage>
        );
    }

    private emptyRow(isLinked: boolean): React.ReactNode {
        let isEmptyMessage = '';
        if (isLinked) {
            isEmptyMessage = Msg.localize('linkedEmpty');
        } else {
            isEmptyMessage = Msg.localize('unlinkedEmpty');
        }

        return (
            <DataListItem key='emptyItem' aria-labelledby="empty-item">
                <DataListItemRow key='emptyRow'>
                    <DataListItemCells dataListCells={[
                        <DataListCell key='empty'><strong>{isEmptyMessage}</strong></DataListCell>
                    ]}/>
                </DataListItemRow>
            </DataListItem>
        )
    }

    private makeRows(accounts: LinkedAccount[], isLinked: boolean): React.ReactNode {
        if (accounts.length === 0) {
            return this.emptyRow(isLinked);
        }

        return (
            <> {

                accounts.map( (account: LinkedAccount) => (
                    <DataListItem id={`${account.providerAlias}-idp`} key={account.providerName} aria-labelledby="simple-item1">
                        <DataListItemRow key={account.providerName}>
                            <DataListItemCells
                                dataListCells={[
                                    <DataListCell key='idp'><Stack><StackItem isFilled>{this.findIcon(account)}</StackItem><StackItem id={`${account.providerAlias}-idp-name`} isFilled><h2><strong>{account.displayName}</strong></h2></StackItem></Stack></DataListCell>,
                                    <DataListCell key='badge'><Stack><StackItem isFilled/><StackItem id={`${account.providerAlias}-idp-badge`} isFilled>{this.badge(account)}</StackItem></Stack></DataListCell>,
                                    <DataListCell key='username'><Stack><StackItem isFilled/><StackItem id={`${account.providerAlias}-idp-username`} isFilled>{account.linkedUsername}</StackItem></Stack></DataListCell>,
                                ]}/>
                            <DataListAction aria-labelledby='foo' aria-label='foo action' id='setPasswordAction'>
                                {isLinked && <Button id={`${account.providerAlias}-idp-unlink`} variant='link' onClick={() => this.unLinkAccount(account)}><UnlinkIcon size='sm'/> <Msg msgKey='unLink'/></Button>}
                                {!isLinked && <Button id={`${account.providerAlias}-idp-link`} variant='link' onClick={() => this.linkAccount(account)}><LinkIcon size='sm'/> <Msg msgKey='link'/></Button>}
                            </DataListAction>
                        </DataListItemRow>
                    </DataListItem>
                ))

            } </>

        )
    }

    private badge(account: LinkedAccount): React.ReactNode {
        if (account.social) {
            return (<Badge><Msg msgKey='socialLogin'/></Badge>);
        }

        return (<Badge style={{backgroundColor: "green"}} ><Msg msgKey='systemDefined'/></Badge>);
    }

    private findIcon(account: LinkedAccount): React.ReactNode {
        const socialIconId = `${account.providerAlias}-idp-icon-social`;
        if (account.providerName.toLowerCase().includes('github')) return (<GithubIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('linkedin')) return (<LinkedinIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('facebook')) return (<FacebookIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('google')) return (<GoogleIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('instagram')) return (<InstagramIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('microsoft')) return (<MicrosoftIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('bitbucket')) return (<BitbucketIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('twitter')) return (<TwitterIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('openshift')) return (<OpenshiftIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('gitlab')) return (<GitlabIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('paypal')) return (<PaypalIcon id={socialIconId} size='xl'/>);
        if (account.providerName.toLowerCase().includes('stackoverflow')) return (<StackOverflowIcon id={socialIconId} size='xl'/>);

        return (<CubeIcon id={`${account.providerAlias}-idp-icon-default`} size='xl'/>);
    }

};

const LinkedAccountsPagewithRouter = withRouter(LinkedAccountsPage);
export {LinkedAccountsPagewithRouter as LinkedAccountsPage};

// themes/src/main/resources/theme/keycloak-preview/account/resources/app/content/linked-accounts-page/linked-accounts-page.component.ts
/*
 * Copyright 2018 Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, OnInit} from '@angular/core';

import {AccountServiceClient} from '../../account-service/account.service';

import {LinkedAccounts} from './linked-accounts-bean.interface';

@Component({
    selector: 'app-linked-accounts-page',
    templateUrl: './linked-accounts-page.component.html',
    styleUrls: ['./linked-accounts-page.component.css']
})
export class LinkedAccountsPageComponent implements OnInit {
    
    private linkedAccounts: LinkedAccounts;
    private redirectUri: string = "http://localhost:8080/auth/realms/master/account/%23/linked-accounts";//resourceUrl + "#/linked-accounts";

    constructor(private accountSvc: AccountServiceClient) {
    }
    
    private linkAccount(providerId: string):void {
        console.log('>>>> redirectUri=' + this.redirectUri)
        this.accountSvc.doGetRequest("/linked-accounts/" + providerId + "?redirectUri=" + this.redirectUri, (res: Response) => this.handleAccountLinkUriRequest(res));
    }
    
    private doGet():void {
        this.accountSvc.doGetRequest("/linked-accounts", (res: Response) => this.handleGetResponse(res));
        //this.accountSvc.doGetNonAccount("http://localhost:8080/auth/admin/realms/master/users?first=0&max=20", (res: Response) => this.handleGetResponse(res));
        //this.accountSvc.doGetNonAccount("http://localhost:8080/auth/admin/master/console/config", (res: Response) => this.handleGetResponse(res));
    }
    
    private doRemove(providerId: string):void {
        this.accountSvc.doDelete("/linked-accounts/" + providerId, (res: Response) => this.handleDeleteResponse(res));
    }
    
    protected handleGetResponse(res: Response) {
        console.log('**** response from Linked Accounts GET ***');
        console.log(JSON.stringify(res));
        console.log(res.json())
        console.log('***************************************');
    }
    
    protected handleAccountLinkUriRequest(res: Response) {
        console.log('**** response from Linked Accounts GET Account Link URI Request ***');
        console.log(JSON.stringify(res));
        console.log('accountLinkUri=' + res.json()['accountLinkUri']);
        console.log('***************************************');
        window.location.replace(res.json()['accountLinkUri']); 
    }
    
    protected handleDeleteResponse(res: Response) {
        console.log('**** response from Linked Accounts DELETE ***');
        console.log(JSON.stringify(res));
        console.log('***************************************');
    }
    
    ngOnInit() {
    }
}

<div class="page-header">
  <h1>{{'linkedAccountsHtmlTitle' | translate}}</h1>
  <hr/>
  <h2>Buttons for manual testing.  See JS Console for output.</h2>
  <div class="card-pf-body row">
      <button class="label label-primary" (click)="doGet()">List All</button>
  </div>
  <div class="card-pf-body row">
    <button class="label label-primary" (click)="linkAccount('github')">Link Account to GitHub</button>
    <button class="label label-primary" (click)="doRemove('github')">Remove GitHub</button>
  </div>
  <div class="card-pf-body row">
    <button class="label label-primary" (click)="linkAccount('stackoverflow')">Link Account to Stack Overflow</button>
    <button class="label label-primary" (click)="doRemove('stackoverflow')">Remove Stack Overflow</button>
  </div>
  <div class="card-pf-body row">
    <button class="label label-primary" (click)="linkAccount('linkedin')">Link Account to LinkedIn</button>
    <button class="label label-primary" (click)="doRemove('linkedin')">Remove LinkedIn</button>
  </div>
  <hr/>
</div>
<div class="col-sm-12 card-pf card-linked-account">
  <div class="card-pf-body row">
    <div class="col-md-3">
      <div class="card-pf-subtitle" id="authorizedProvidersSubTitle">
        {{'authorizedProvider' | translate}}
      </div>
      <div class="introMessage" id="authorizedProvidersSubMessage">
        <p>{{'authorizedProviderMessage' | translate}}</p>
      </div>
    </div>
    <div class="col-md-9">
      <div class="list-group list-view-pf list-view-pf-view" id="authorizedProvidersList">
        <div class="list-group-item">
          <div class="list-view-pf-actions">
            <a href="#" data-toggle="modal" data-target="#myModal">{{'doRemove' | translate}}</a>
          </div>
          <div class="list-view-pf-main-info">
            <div class="list-view-pf-left">
              <span class="fa fa-google list-view-pf-icon-sm"></span>
            </div>
            <div class="list-view-pf-body">
              <div class="list-view-pf-description">
                <div class="list-group-item-heading">
                  Google
                </div>
                <div class="list-group-item-text">
                  <span class="label label-primary">{{'socialLogin' | translate}}</span>
                </div>
              </div>
              <div class="list-view-pf-additional-info">
                <span class="fa fa-user"> </span>  zhutaoredhat
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-sm-12 card-pf card-linked-account">
  <div class="card-pf-body row">
    <div class="col-md-3">
      <div class="card-pf-subtitle" id="identityProviderSubTitle">
        {{'identityProvider' | translate}}
      </div>
      <div class="introMessage" id="identityProviderSubMessage">
        <p>{{'identityProviderMessage' | translate}}</p>
      </div>
    </div>
    <div class="col-md-9">
      <div class="list-group list-view-pf list-view-pf-view " id="identityProviderList">
        <div class="list-group-item">
          <div class="list-view-pf-actions">
            <a href="#">{{'doLink' | translate}}</a>
          </div>
          <div class="list-view-pf-main-info">
            <div class="list-view-pf-left">
              <span class="fa fa-facebook list-view-pf-icon-sm"></span>
            </div>
            <div class="list-view-pf-body">
              <div class="list-view-pf-description">
                <div class="list-group-item-heading">
                  Facebook
                </div>
                <div class="list-group-item-text">
                  <span class="label label-primary">{{'socialLogin' | translate}}</span>
                </div>
              </div>
              <div class="list-view-pf-additional-info">
              </div>
            </div>
          </div>
        </div>

        <div class="list-group-item">
          <div class="list-view-pf-actions">
            <a href="#">{{'doLink' | translate}}</a>
          </div>
          <div class="list-view-pf-main-info">
            <div class="list-view-pf-left">
              <span class="fa fa-github list-view-pf-icon-sm"></span>
            </div>
            <div class="list-view-pf-body">
              <div class="list-view-pf-description">
                <div class="list-group-item-heading">
                  Github
                </div>
                <div class="list-group-item-text">
                  <span class="label label-primary">{{'socialLogin' | translate}}</span>
                </div>
              </div>
              <div class="list-view-pf-additional-info">
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">{{'removeAccess' | translate}}</h4>
      </div>
      <div class="modal-body">
        {{'removeAccessMessage' | translate}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{'doCancel' | translate}}</button>
        <button type="button" class="btn btn-primary">{{'doRemove' | translate}}</button>
      </div>
    </div>
  </div>
</div>
<!-- End Modal -->
