// themes/src/main/resources/theme/keycloak-preview/account/resources/app/content/linked-accounts-page/linked-accounts-page.component.ts
/*
 * Copyright 2018 Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, OnInit} from '@angular/core';


@Component({
    selector: 'app-linked-accounts-page',
    templateUrl: './linked-accounts-page.component.html',
    styleUrls: ['./linked-accounts-page.component.css']
})
export class LinkedAccountsPageComponent implements OnInit {

    constructor() {
    }
    
    ngOnInit() {
    }
}

<div class="page-header">
  <h1>{{'linkedAccountsHtmlTitle' | translate}}</h1>
  <hr/>
  <h2>Buttons for manual testing.  See JS Console for output.</h2>
  <div class="card-pf-body row">
      <button class="label label-primary" (click)="doGet()">List All</button>
  </div>
  <div class="card-pf-body row">
    <button class="label label-primary" (click)="linkAccount('github')">Link Account to GitHub</button>
    <button class="label label-primary" (click)="doRemove('github')">Remove GitHub</button>
  </div>
  <div class="card-pf-body row">
    <button class="label label-primary" (click)="linkAccount('stackoverflow')">Link Account to Stack Overflow</button>
    <button class="label label-primary" (click)="doRemove('stackoverflow')">Remove Stack Overflow</button>
  </div>
  <div class="card-pf-body row">
    <button class="label label-primary" (click)="linkAccount('linkedin')">Link Account to LinkedIn</button>
    <button class="label label-primary" (click)="doRemove('linkedin')">Remove LinkedIn</button>
  </div>
  <hr/>
</div>
<div class="col-sm-12 card-pf card-linked-account">
  <div class="card-pf-body row">
    <div class="col-md-3">
      <div class="card-pf-subtitle" id="authorizedProvidersSubTitle">
        {{'authorizedProvider' | translate}}
      </div>
      <div class="introMessage" id="authorizedProvidersSubMessage">
        <p>{{'authorizedProviderMessage' | translate}}</p>
      </div>
    </div>
    <div class="col-md-9">
      <div class="list-group list-view-pf list-view-pf-view" id="authorizedProvidersList">
        <div class="list-group-item">
          <div class="list-view-pf-actions">
            <a href="#" data-toggle="modal" data-target="#myModal">{{'doRemove' | translate}}</a>
          </div>
          <div class="list-view-pf-main-info">
            <div class="list-view-pf-left">
              <span class="fa fa-google list-view-pf-icon-sm"></span>
            </div>
            <div class="list-view-pf-body">
              <div class="list-view-pf-description">
                <div class="list-group-item-heading">
                  Google
                </div>
                <div class="list-group-item-text">
                  <span class="label label-primary">{{'socialLogin' | translate}}</span>
                </div>
              </div>
              <div class="list-view-pf-additional-info">
                <span class="fa fa-user"> </span>  zhutaoredhat
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-sm-12 card-pf card-linked-account">
  <div class="card-pf-body row">
    <div class="col-md-3">
      <div class="card-pf-subtitle" id="identityProviderSubTitle">
        {{'identityProvider' | translate}}
      </div>
      <div class="introMessage" id="identityProviderSubMessage">
        <p>{{'identityProviderMessage' | translate}}</p>
      </div>
    </div>
    <div class="col-md-9">
      <div class="list-group list-view-pf list-view-pf-view " id="identityProviderList">
        <div class="list-group-item">
          <div class="list-view-pf-actions">
            <a href="#">{{'doLink' | translate}}</a>
          </div>
          <div class="list-view-pf-main-info">
            <div class="list-view-pf-left">
              <span class="fa fa-facebook list-view-pf-icon-sm"></span>
            </div>
            <div class="list-view-pf-body">
              <div class="list-view-pf-description">
                <div class="list-group-item-heading">
                  Facebook
                </div>
                <div class="list-group-item-text">
                  <span class="label label-primary">{{'socialLogin' | translate}}</span>
                </div>
              </div>
              <div class="list-view-pf-additional-info">
              </div>
            </div>
          </div>
        </div>

        <div class="list-group-item">
          <div class="list-view-pf-actions">
            <a href="#">{{'doLink' | translate}}</a>
          </div>
          <div class="list-view-pf-main-info">
            <div class="list-view-pf-left">
              <span class="fa fa-github list-view-pf-icon-sm"></span>
            </div>
            <div class="list-view-pf-body">
              <div class="list-view-pf-description">
                <div class="list-group-item-heading">
                  Github
                </div>
                <div class="list-group-item-text">
                  <span class="label label-primary">{{'socialLogin' | translate}}</span>
                </div>
              </div>
              <div class="list-view-pf-additional-info">
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">{{'removeAccess' | translate}}</h4>
      </div>
      <div class="modal-body">
        {{'removeAccessMessage' | translate}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{{'doCancel' | translate}}</button>
        <button type="button" class="btn btn-primary">{{'doRemove' | translate}}</button>
      </div>
    </div>
  </div>
</div>
<!-- End Modal -->

// themes/src/main/resources/theme/keycloak-preview/account/resources/app/content/linked-accounts-page/LinkedAccountsPage.tsx
/* 
 * Copyright 2018 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';
 
export interface LinkedAccountsPageProps {
}
 
export class LinkedAccountsPage extends React.Component<LinkedAccountsPageProps> {
    
    constructor(props: LinkedAccountsPageProps) {
        super(props);
    }

    render() {
        return (
            <div>
              <h2>Hello Linked Accounts Page</h2>
            </div>
        );
    }
};
