// themes/src/main/resources/theme/keycloak-preview/account/resources/app/app.component.ts
/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, HostListener} from '@angular/core';

import {TranslateService} from '@ngx-translate/core';

import {ResponsivenessService, ContentWidthClass, MenuClickListener} from "./responsiveness-service/responsiveness.service";

declare const locale: string;

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent implements MenuClickListener {
    
    private contentWidthClass: ContentWidthClass = this.respSvc.calcSideContentWidthClass();
    
    constructor(translate: TranslateService, private respSvc: ResponsivenessService) {
        // this language will be used as a fallback when a translation isn't found in the current language
        translate.setDefaultLang('en');

        // the lang to use, if the lang isn't available, it will use the current loader to get them
        translate.use(locale);
        
        this.respSvc.addMenuClickListener(this);
    }
    
    public menuClicked() : void {
        this.contentWidthClass = this.respSvc.calcSideContentWidthClass();
    }
    
    @HostListener('window:resize', ['$event'])
    private onResize(event: any) {
        this.contentWidthClass = this.respSvc.calcSideContentWidthClass();
    }
    
}
<!--<div *ngIf="kcService.authenticated()">
    <app-top-nav [showSideNav]="showSideNav"></app-top-nav>
</div>

<app-side-nav *ngIf="showSideNav"></app-side-nav>


<div class="container-fluid container-pf-alt-nav-pf-vertical-alt {{this.contentWidthClass}}"> <!-- collapsed-nav hidden-nav 

    <router-outlet></router-outlet>
</div>-->


<vertical-nav *ngIf="showSideNav"></vertical-nav>

// themes/src/main/resources/theme/keycloak-preview/account/src/app/App.tsx
/*
 * Copyright 2018 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as React from 'react';

import {KeycloakService} from './keycloak-service/keycloak.service';

import {PageNav} from './PageNav';
import {PageToolbar} from './PageToolbar';
import {makeRoutes} from './ContentPages';

import {
    Brand,
    Page,
    PageHeader,
    PageSection,
    PageSidebar,
} from '@patternfly/react-core';

declare function toggleReact(): void;
declare function isWelcomePage(): boolean;
declare function loggedInUserName(): string;

declare const locale: string;
declare const resourceUrl: string;

declare const brandImg: string;
declare const brandUrl: string;

export interface AppProps {};
export class App extends React.Component<AppProps> {
    private kcSvc: KeycloakService = KeycloakService.Instance;

    public constructor(props: AppProps) {
        super(props);
        toggleReact();
    }

    public render(): React.ReactNode {
        toggleReact();

        // check login
        if (!this.kcSvc.authenticated() && !isWelcomePage()) {
            this.kcSvc.login();
        }

        const username = (
            <span style={{marginLeft: '10px'}} id="loggedInUser">{loggedInUserName()}</span>
        );
        const Header = (
            <PageHeader
                logo={<a id="brandLink" href={brandUrl}><Brand src={brandImg} alt="Logo" className="brand"/></a>}
                toolbar={<PageToolbar/>}
                avatar={username}
                showNavToggle
            />
        );

        const Sidebar = <PageSidebar nav={<PageNav/>} />;

        return (
            <span style={{ height: '100%'}}>
                <Page header={Header} sidebar={Sidebar} isManagedSidebar>
                    <PageSection>
                        {makeRoutes()}
                    </PageSection>
                </Page>
            </span>
        );
    }
};
